<?xml version="1.0"?>
<robot name="duda" xmlns:xacro="http://ros.org/wiki/xacro">
     <!-- Include Materials -->
     <material name="Black">
         <color rgba="0.0 0.0 0.0 1.0"/>
     </material>
     <material name="Red">
         <color rgba="0.8 0.0 0.0 1.0"/>
     </material>
     <material name="White">
         <color rgba="1 1 1 1"/>
     </material>

     <!--Include URDF/XACRO files -->
     <xacro:include filename="$(find duda_description)/urdf/wheel.urdf.xacro" />

     <!-- Constants -->
     <xacro:property name="M_PI" value="3.14159"/>

     <!-- Middle Compartment Dimensions -->
     <xacro:property name="middle_comp_length" value="2.6" />
     <xacro:property name="middle_comp_width" value="0.6" />
     <xacro:property name="middle_comp_height" value="0.4" />

     <!-- Front Compartment Dimensions -->
     <xacro:property name="front_comp_length" value="1.6" />
     <xacro:property name="front_comp_width" value="5.6" />
     <xacro:property name="front_comp_height" value="0.4" />

    <!-- Wheel Mounting Positions -->
    <xacro:property name="wheelbase" value="0.5120" />
    <xacro:property name="track" value="0.645" />
    <xacro:property name="wheel_vertical_offset" value="0.03282" /> 

    <!-- Wheel Properties for Collision -->
    <xacro:property name="wheel_length" value="0.1143" />
    <xacro:property name="wheel_radius" value="0.1651" />

    <!-- Base link / Middle Compartment -->
    <link name="base_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>    
            <geometry>
                <box size="0.480 0.631 0.355"/>
            </geometry>
            <material name="Black" />
        </visual>
    </link>

     <!-- Duda wheel macros -->
    <xacro:duda_wheel wheel_prefix="front_left">
        <origin xyz="0 ${track/2} 0" rpy="0 0 0" />
    </xacro:duda_wheel>

    <xacro:duda_wheel wheel_prefix="front_right">
        <origin xyz="0 ${-track/2} 0" rpy="0 0 0" />
    </xacro:duda_wheel>

</robot>
